# Windsurf Coding Style Rules

testing_framework: Unity
build_system: CMake

c:
  pointer_declaration_style: identifier
  # This enforces 'char *foo' instead of 'char* foo' or 'char * foo'
  # Applies to all pointer types in declarations and definitions.
  # Other style rules can be added here as needed.
  clang_tidy_checks:
    - readability-prefer-const-declarations

# Git / Version Control Rules
git:
  avoid_amend_commits: true
  # Prefer creating new commits over amending existing ones, especially
  # once commits have been shared or are part of a merge history.
